Mappings:
  InstanceMap:
    us-east-1:
      dev: t2.micro
      prod: m1.small
    us-west-1: 
      dev: m1.small
      prod: m1.large
  AMIMap:
    us-east-1:
      dev: ami-0b09ffb6d8b58ca91
      prod: ami-0b09ffb6d8b58ca91
    us-west-1:
      dev: ami-0d9e15a8edf01ec21
      prod: ami-0d9e15a8edf01ec21
Parameters: 
  EnvironmentParameter: 
    Type: String
    Default: dev
    AllowedValues: 
      - dev
      - prod
    Description: Enter dev or prod.
Resources:
  MyEC2Instance:
    Type: AWS::EC2::Instance
    Properties:
      ImageId: !FindInMap [AMIMap, !Ref "AWS::Region", Ref: EnvironmentParameter]
      InstanceType: !FindInMap [InstanceMap,!Ref "AWS::Region", Ref: EnvironmentParameter]